### ISSUE TITLE
Browser support documentation?

### ISSUE THREAD

**Issue by jericopulvera** [tailwindcss/discuss#131]

**Comment by dmitrykurmanov** [comment]
I can't find any notes about browser support. Could anyone please tell about it?

**Comment by adamwathan** [comment]
With Tailwind browser compatibility is sort of a weird topic. Because everything is just tiny utility classes that only apply one property, its really more up to the user to decide what features they want to use.

For example, Tailwind has a bunch of Flexbox stuff but Flexbox wont work on IE 9, so `flex` or `justify-between` aren't going to work there. That doesn't really mean Tailwind is inherently incompatible with IE 9 though, it's only incompatible if you choose to use CSS features that aren't supported in IE 9.

Unlike other frameworks that provide higher level abstractions (like Bootstrap for example), you never really have to worry about some abstraction we provide being built on top of some modern browser feature without you knowing about it. So you're never going to find a class like `form-control` and not know if it's IE 9 compatible because maybe it's built with Flexbox internally — any time you are using Flexbox with Tailwind it's very explicit.

As a general rule we only include features in core if they are supported in IE 11 + evergreen browsers, but over time hoping to be able to include more useful stuff that's not supported in IE 11, like CSS Grid. We already include some things that aren't supported in IE 11, like utilities for `position: sticky` and `object-fit`/`object-position` but as always you can simply choose not to use those features if you need to support older browsers.
