### ISSUE TITLE
Improvement of Installation Doc.

### ISSUE THREAD

**Issue by clevonnoel** [tailwindcss/discuss#136]
I see an inconsistency in the installation part of the documentation. The following is my recommendation to improve the installation part of the documentation.

In the "_NPM_" section, item 2, it is recommended to create a `tailwind.js`, yet when using the CLI utility without providing a filename, the file generated is `tailwind-config.js`.

````
./node_modules/.bin/tailwind init [filename]
````

 In addition, there are  other parts of the document that references `tailwind.js` while other parts references `tailwind-config.js`

I would suggest that the default file generated should be as recommended `tailwind.js` and to update other references in the doc. to use `tailwind.js`instead of `tailwind-config.js`. I believe that this change will improve the documentation to make it clear and consistent. I would love to hear your thoughts. I am more than happy to submit a PR.

**Comment by taylorbryant** [comment]
I think there's some misunderstanding here. When using the `init` function, a `tailwind.js` file is created.

The references to `/path/to/your/tailwind-config.js` in the docs aren't referencing an actual filepath, they are just saying generically saying "path to your Tailwind config."

**Comment by adamwathan** [comment]
Yeah like @taylorbryant mentioned the only time we ever say `tailwind-config.js` is in the examples where we say `/path/to/your/tailwind-config.js`, which is just trying to make it clear that you should be specifying the "path to your Tailwind config" file there, since you can put that file anywhere you want (I often put it in my CSS folder.)

`tailwind init` generates a `tailwind.js` file, not a `tailwind-config.js` file:

https://github.com/tailwindcss/tailwindcss/blob/master/src/cli.js#L43

Still happy to accept improvements that make things more clear. I'm hesitant to say `./tailwind.js` everywhere in the docs because it's no longer clear that it should be the path to your own config file (wherever you've put it), not that hardcoded string.

**Comment by clevonnoel** [comment]
Thanks, @adamwathan and @taylorbryant  for your feedback.  Certainly makes sense.
