### ISSUE TITLE
What is the naming convention for the text sizing variants?

### ISSUE THREAD

**Issue by abepark01** [tailwindcss/discuss#148]
Hello!

I would like to add new text size to the `tailwind.config.js` file for font-size `10rem`

Looking at the pre-defined sizes... I see that `3rem` maps to the class `text-5xl`.
I don't quite see the pattern/connection between the class name '`text-5xl` since `3rem` is 3 times the base font size of `16px`.
I thought it would be `text-3xl` for `3rem`.

So, it would be great if I could get some context between the naming conventions for text sizes? 

Is the number suffix just a sequence number?
Am I overthinking this?

Thanks!

[Text Sizing](https://tailwindcss.com/docs/text-sizing)

**Comment by adamwathan** [comment]
Hey Abe! Yep it's just a sequence number, there's no math involved with those.

I would probably use 7 or 8 personally because the jump from 3rem to 10rem is pretty significant, and you want to leave yourself room in case you need to add a new size in between, but nothing really wrong with just using the next number in the sequence either.

You could also give it a new name if you wanted that separates it from the scale, like `text-hero` or something.

**Comment by abepark01** [comment]
Hey @adamwathan, 

That makes sense; Thanks!
I was punching in a whole bunch of numbers into my calculator, trying to figure out a pattern 😅
