### ISSUE TITLE
Tailwind + CSS Modules not getting processed by CSSPurge correctly.

### ISSUE THREAD

**Issue by marbuser** [tailwindcss/discuss#172]
I reported this at purgecss (https://github.com/FullHuman/purgecss/issues/135) since I think it might be a bug, but I think it's also worth asking here and seeing if anyone has any ideas or if someone has had this issue previously and managed to solve it.

To summarise what I said in the PurgeCSS issue;
I'm using VueJS + CSSModules, Tailwind (shadowLookup), and CSSPurge. CSS Modules and Tailwind itself is working fine and even CSSPurge to an extent is doing it's job properly. However, there is a small issue in regards to it leaving redundant classes behind and I'm not sure how to solve it.

For example, this button class;
```
.button {
  @apply no-underline py-2 px-4 font-bold text-white rounded select-none;
}
```

Would compose;
```
<hash> : {
  border-radius: .25rem;
  color: #fff;
  font-weight: 700;
  padding: .5rem 1rem;
  text-decoration: none;
  user-select: none
}
```

Which means that the classes that it was composed of (no-underline, py-2, etc...) are now redundant. CSSPurge leaves them in the final CSS though on build. You can see an example of this if you build my repo here; https://github.com/marbuser/vue-purgecss-example

If I manually remove these classes from the css, the project still works as intended so I'm not sure why CSSPurge is leaving these in.

Was wondering if anyone else has encountered this issue before and if they managed to fix it somehow?

**Comment by adamwathan** [comment]
So this is probably because of how PurgeCSS detects if a class is used or not.

Basically all it does is iterate over all the classes in your CSS, then look through your templates to see if it can find that class _anywhere in the file_.

So it looks through CustomButton.vue for example, sees you using `no-underline` inside the `<style>` block and determines you are using it, so it keeps it.

I think the only way to avoid this is to write your own custom extractor that's a lot more intelligent and only looks for classes in the `template` and `script` blocks of Vue single file components and ignores the `style` block.

**Comment by marbuser** [comment]
@adamwathan Thanks for that. I will take a look into it and have a play around with it. I'm definitely not the best with Regex though so might have to do some learning first!

**Comment by ky-is** [comment]
Thanks for investigating this! It's been confusing me too. Getting good results with `/<style[^]+?<\/style>/gi` (functionality should be the same, just preference).

Just to note, I think you shouldn't need `whitelist: ['html', 'body'],` as long as you provide PurgeCSS your html file; it picked up those selectors for me.
