### ISSUE TITLE
The best approach for pseudo-elements?

### ISSUE THREAD

**Issue by CDNRocket** [tailwindcss/discuss#184]
What is the best approach for work with pseudo-elements like :before, :after, etc?
We need to create custom utilities/components?

Maybe should be a good idea to have a feature for this like: text-red:before?

**Comment by tlgreg** [comment]
Anything (almost?) could be applied to a pseudo-element. I don't think default config should include it though.

I could imagine it being a variant for the modules, which could be made with a plugin too if not in the core.

**Comment by hacknug** [comment]
You could probably [use a plugin to register a new variant](https://github.com/tailwindcss/tailwindcss/releases#registering-new-variants-from-plugins) to do that. This was introduced in v0.6.2 and it's probably the easiest way to deal with your issue since you'll be able to carry that plugin between projects and also publish it as an npm package.
