### ISSUE TITLE
Zebra Striping on Tables

### ISSUE THREAD

**Issue by tance77** [tailwindcss/discuss#204]
Could we possibly see new classes for zebra striping on tables in the future? 

**For Example:** 
* 'striped-blue-lightest',
* 'striped-green-lightest',
* 'striped-orange-lightest'

**Comment by hacknug** [comment]
You have [this plugin](https://github.com/drehimself/tailwindcss-tables) if you want to add Bootstrap-like tables to your projects. And if you just want to have those classes available, you could either create your own plugin for that or simply add those classes to your stylesheet if it's goin to be a one project thing.

I don't think Tailwind should provide them in core since this would be too coupled to a given design implementation.

**Comment by WalrusSoup** [comment]
A utility class to apply a style to every 'nth' would be helpful for striping. Not sure how clean it would be to inline something like that, but it may work based on elements?

```
<table class="w-full tr-even:bg-grey-light">
<div class="w-full {element}-{even|odd}:{style}"> 
```

**Comment by samselikoff** [comment]
Believe this is possible with v1.1.0! From [the release notes](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.1.0):

![image](https://user-images.githubusercontent.com/2922250/64432408-6defb100-d08a-11e9-88b5-6fa771888c71.png)

**Comment by tance77** [comment]
Yup it is. I closed it because of that :)
