### ISSUE TITLE
About component-based architectures

### ISSUE THREAD

**Issue by equinusocio** [tailwindcss/discuss#213]
Just want to discuss about Tailwind and component-based architectures like React, Vue and Angular. I tried to test it with vue-cli and extracting the css (this generate external css files rather than inline it). 

Here the result:

A `412kb` css were loaded just using one `@apply` on a button. This is the first fail because i'm applying a bunch of classes in my component, i don't need the full bundle. The component class is inside the bundle.

```css
.btn {
  @apply .font-bold .py-2 .px-4 .rounded .bg-red .text-white;
}
```

<img width="600px" src="https://thepracticaldev.s3.amazonaws.com/i/ts71w5ewta7il59etde4.png" />

---

Here the same test but lazy loading the component. It include the `400kb` css bundle beside the component css (where the above class and `@apply` is used). The bundle contains all the class combinations, media queries, selector hacks, and so on, even if don't require them in my component.

<img width="600px" src="https://thepracticaldev.s3.amazonaws.com/i/ar2fqv6ep0j335vu730o.png" />

---

<img width="600px" src="https://thepracticaldev.s3.amazonaws.com/i/d9f4tbmduyke30361wqj.png" />

This isn't good and i think it's a bit anti-pattern. Can we talk about this behaviour? Is this caused by the  basic implementation?

**Comment by equinusocio** [comment]
Yes i followed the installation guide. Should removing them solve this issue? It will work also with file chunkins?

**Comment by adamwathan** [comment]
Well `@tailwind utilities` says "render all of the utilities here", so the behavior you're seeing is expected — you're explicitly telling Tailwind to create that 400kb worth of CSS. If you don't want to create those classes, you can remove `@tailwind utilities` from your base CSS file or root component, wherever you've added it.

**Comment by equinusocio** [comment]
Of course...@adamwathan. The point here isn't the weight of the bundle, but the fact that i can't use `sm:bg-green` and all other utilities when using @apply.

**Comment by equinusocio** [comment]
@adamwathan so to use it with a component based arch we don't need to add utilities as said here:
https://tailwindcss.com/docs/installation#3-use-tailwind-in-your-css

> Use the @tailwind directive to inject Tailwind's preflight and utilities styles into your CSS.

**Comment by equinusocio** [comment]
No responses?

**Comment by adamwathan** [comment]
I don’t understand what you want. You want the utilities but at the same time you want them to use 0kb of CSS? 

We have a whole section of the documentation on controlling file size that includes multiple different strategies if that’s what you are asking. If not please explain what you’re asking in more detail with more examples because I’m not sure how to help.

**Comment by adamwathan** [comment]
You don’t need to render the utilities using `@tailwind utilities` to be able to use them with `@apply`, Tailwind can still apply any utilities that it would have generated even if you aren’t explicitly generating them.

So if you don’t want to render the utilities and only want to reference them with `@apply` inside of components, just don’t include `@tailwind utilities` anywhere in your CSS.

If you want to use utilities in your HTML then you do have to use `@tailwind utilities` in your CSS otherwise those classes will never actually exist.

If you want to use utilities in your HTML but only want to serve the minimum CSS possible to the client based on the classes you actually use, I recommend using purgecss to strip out unused CSS.

https://tailwindcss.com/docs/controlling-file-size#removing-unused-css-with-purgecss

If none of that answers your question please clarify what you actually want to know and I’ll do my best to help.

**Comment by equinusocio** [comment]
Inside my component css i need to include just one utility and i don't have a global css to purge. Is this the correct usage (example)?


```html
<style lang="postcss" scoped>
.btn {
  @apply font-bold py-2 px-4 rounded bg-red text-white;
}

.btn:hover {
  @apply bg-blue-dark
}

@screen md {
  .btn {
    @apply bg-green font-normal;
  }
}
</style>
```

**Comment by adamwathan** [comment]
What you have there should work, although depending on the Vue project I have seen `lang="postcss"` cause problems.

I'm still a bit confused because you say:

> i need to include just one utility

...but in your example there are 8 utilities listed, not one.

**Comment by equinusocio** [comment]
> ...but in your example there are 8 utilities listed, not one.

yes i have made it to show the point. I was thinking that to use @apply i had to import the utilities, but as you said tailwind works just importing the js.

> I have seen lang="postcss" cause problems.

Yes, it dependes on some configuration but is required by the editor to correct highlight and lint the code
