### ISSUE TITLE
New VueCli project with TailwindCSS fails to load styles

### ISSUE THREAD

**Issue by stackus** [tailwindcss/discuss#287]
Example Repo: https://github.com/stackus/tailwind-issue

Installed using the instructions on the TailwindCSS site.

1. `npm i -D tailwindcss`
2. `tailwind init`
3. Added tailwind to the postcss.config.js file
4. Created and added tailwind includes to a `assets/css/main.css` file.

After adding tailwind the page styles do not show the `bg-purple` style added to a div and also loses the styles added from the component styles.

Browsers: Firefox 67.0.4, Chrome 75.0.3770.100
OS: Windows 10

Disabling the TailwindCSS inline styles (1751 in total), by clicking on the eye icon in the Style Editor, will allow the other styles to work and the page will show the original styling installed with the base Vue CLI install. No TailwindCSS styles are ever applied.

**Comment by tlgreg** [comment]
There is no such color in the default config as `bg-purple`, every color has nine shades, you can use `bg-purple-400` for example from the default palette.
Color docs: https://tailwindcss.com/docs/customizing-colors

Other than that the example works. Other styles are also applied, no div loses its css.

The page looks different because there is a css normalization/base style applied so it will not look the same.

One note though with this approach.
When you import a global css file in your main js it will end up at the end of your css bundle.

With vue it's actually better to import the css file in your `App.vue` then the bundle will start with that global css and component's css will come after it.
This is only an issue if the same specificity rules apply to the same element.

Also, an example vue starter:
https://github.com/tailwindcss/setup-examples/tree/master/examples/vue-cli

**Comment by stackus** [comment]
Good, and of course it was something boneheaded. I had also tried putting it as the src attribute in my App component and did not see any difference. Personally prefer it there so putting it back now.
