### ISSUE TITLE
font-display vs font-body

### ISSUE THREAD

**Issue by justinekizhak** [tailwindcss/discuss#293]
What is the difference between `font-display` and `font-body` when you are configuring it in `tailwind.config.js`?

In https://github.com/tailwindcss/discuss/issues/277 it's said I need to add `font-body` to my HTML to use that font.    
But my `tailwind.config.js` is
```javascript
module.exports = {
  theme: {
      fontFamily: {
          display: ['Futura', 'sans-serif'],
          body: ['Futura', 'sans-serif'],
      },
      extend: {}
  },
  variants: {},
  plugins: []
}
```
and adding either `font-display` or `font-body` works.

Is using one advantageous over the other?

**Comment by adamwathan** [comment]
So all you're doing is changing the class name, Tailwind doesn't care at all what keys you use there. There's nothing special about the strings `display` or `body`, you could totally do something like this and it's exactly the same:

```js
module.exports = {
  theme: {
      fontFamily: {
          bananas: ['Futura', 'sans-serif'],
          cookies: ['Futura', 'sans-serif'],
      },
      extend: {}
  },
  variants: {},
  plugins: []
}
```

Tailwind will generate classes named `font-bananas` and `font-cookies` that apply those fonts.

You can do whatever you want with any of those classes. If you want to set a default font for your site, add whatever class has your default font stack to the body tag:

```html
<html>
<!-- ... -->
<body class="font-cookies">
  <!-- ... -->
</body>
</html>
```

There's no real reason for specifying the same font stack for two classes like you have in your config though, because all you are doing is generating two classes that do the same thing which isn't super useful.

Usually you would have something like this:

```js
module.exports = {
  theme: {
      fontFamily: {
          display: ['League Gothic', 'sans-serif'],
          body: ['Arial', 'sans-serif'],
      },
      extend: {}
  },
  variants: {},
  plugins: []
}
```

...and then if you wanted to use `font-body` as your default font, again you'd just add that class to the body tag.

Again, `display` and `body` mean nothing, you could call them `headline` and `content` or `title` and `copy` or `peepee` and `poopoo`, they just control what the classes are named.

**Comment by justinekizhak** [comment]
Thanks
