### ISSUE TITLE
Basic Newbie: command not found: tailwind

### ISSUE THREAD

**Issue by Loungagna** [tailwindcss/discuss#304]
I'm trying to start using tailwind.
In my project root folder, I type "npx tailwind init"
After various fetch of modules, I get glorious:
command not found: tailwind

Am I missing something, and/or doing something wrong?

**Comment by TobiObeck** [comment]
Whats your npm version?
Type the command `npm --version`
NPX comes bundled with NPM version 5.2+
What does your package.json look like?

Watch the video closely and look if you did anything differently.
https://tailwindcss.com/course/setting-up-tailwind-and-postcss/

**Comment by Loungagna** [comment]
npm is 6.10.1

and package.json for now is:
{
  "repository": {},
  "license": "MIT",
  "scripts": {
    "deploy": "webpack --mode production",
    "watch": "webpack --mode development --watch"
  },
  "dependencies": {
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.0",
    "copy-webpack-plugin": "^4.5.0",
    "css-loader": "^3.1.0",
    "mini-css-extract-plugin": "^0.4.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "uglifyjs-webpack-plugin": "^1.2.4",
    "webpack": "4.4.0",
    "webpack-cli": "^3.3.6"
  }
}

**Comment by adamwathan** [comment]
Looks like you never installed Tailwind. You need to run `npm install tailwindcss --save-dev`.

Full installation instructions here, follow them step by step and you should be good:

https://tailwindcss.com/docs/installation

**Comment by ehne** [comment]
Also, probably should add that the npm repo is not `tailwind` its actually `tailwindcss`
so running: `npx tailwindcss init` should create the config file!.
hope this was helpful!

**Comment by tlgreg** [comment]
`tailwind` is the command's name, it works if you installed `tailwindcss` in the project, which is the intended use case, not a global install. The documentation does provide you the steps to install the package first as linked above.

npx has a feature when it can't find a command (local or global) it fetches a package from npm with the same name as the command, installs it globally (in a temporary cache) and tries to execute it as a CLI command.
If you installed `tailwindcss` first, this would not happen as the command is found on the machine.

I actually dislike this implicit behavior of npx, I think it's more harm, then good.

**Comment by apieceofbart** [comment]
This is very confusing, I assumed that running `npx tailwind` would fetch tailwind just like it does for every other use case of `npx`
Why not just change the command in docs to be `npx tailwindcss` and avoid confusion?

**Comment by TobiObeck** [comment]
I'll try to explain this: **tailwindcss** is a [npm package](https://www.npmjs.com/package/tailwindcss).

When you enter `npm install tailwindcss` this package will be installed locally in the current folder. Notice the new node_modules folder in the same folder. If you enter `npm install tailwindcss -g` the package within the node_modules folder will be installed in a general location of your computer. For example on Windows it is `C:\Users\YOUR_NAME\AppData\Roaming\npm`.

Inside of the node_modules folder is a .bin folder that contains executable files called `tailwind` (Mac/Linux) and `tailwind.cmd` (Windows). These files are actually executed under the hood to perform tasks like `init` or `build`. Notice these are called tailwind~~css~~ without css at the end.

Typing in `npx tailwind init` will run the executable that is already installed.

Now if you run `npx tailwindcss init` up to three things will happen. npx looks at you local directory if taildwindcss is installed in a node_modules folder. If this is not the case it looks if it is installed in the global directory. If this is also not  the case the package is installed on the fly and afterwards deleted.

Typing in `npx tailwindcss init` will either install tailwind on the fly or use an existing installation and run the `tailwind` executable under the hood, because it has been specified in the bin property of the tailwind package.json.

Regarding the confusion I am not sure wether the documentation needs improvement.
Maybe [this sentence](https://tailwindcss.com/docs/installation/#3-create-your-tailwind-config-file-optional) could be splitted up into multiple shorter ones to make the meaning a bit more clear:
> If you'd like to customize your Tailwind installation, you can generate a config file for your project using the Tailwind CLI utility included when you install the tailwindcss npm package:

https://tailwindcss.com/docs/installation/#3-create-your-tailwind-config-file-optional

**Comment by apieceofbart** [comment]
@TobiObeck I know how npm works, thank you :)
I just wanted to point out that's not how all of other packages use `npx` - it is expected for things to work without any previous installation - that's the purpose of `npx`. If you ask people to run `npx tailwind init` and assume there's something installed before then it's not what I would expect - hence the confusion.
I agree the docs mention installing, I was just scanning text quickly and copied `npx tailwind build` command

**Comment by ackvf** [comment]
So, I have inherited a large codebase and I just needed the compiled css from it. I have never heard about tailwind and then I finally found a CLI command to build the css without having to install locally anything, the gold `npx`.

Well, not really, because obviously I ended up here, anyway thanks for the lesson. I always used the `npx` for the ability to temporarily install and execute an arbitrary command. I didn't know it can be used to execute an npm package in a same way as a script in package.json such as this `"tsc": "tsc"` does.

I guess that this behaviour is the one that stuck with the users and so this `npx tailwind build styles.css -o output.css` is really confusing. Thanks @apieceofbart for pointing out `tailwindcss`.
I used this command `npx tailwindcss build styles.css -o output.css` instead and it worked like a charm.

**Comment by adamwathan** [comment]
Has anyone considered just submitting a PR that adds another bin entry to our package.json file named “tailwindcss”? I will merge it 😋

**Comment by ackvf** [comment]
I don't know how that works 😢

**Comment by ackvf** [comment]
I think the `npx tailwind` should be with `--no-install`
