### ISSUE TITLE
Using this with email clients and mobile browsers?

### ISSUE THREAD

**Issue by natiki** [tailwindcss/discuss#307]
Hi,

1) Having had a look at the https://tailwindcss.com/docs/browser-support it appears that the framework does not consider mobile browsers?

2) And I realise this is targeted at a browser, but has anyone got any experience with how well the framework works with email clients? In particular GMail, Outlook and Thunderbird? Or perhaps there is a framework like this more directed at email clients as that is a whole set of problems different to browser support.

**Comment by hacknug** [comment]
1. Since Tailwind only generates regular CSS, this is 100% related to the properties in the generated CSS. Browser support will vary depending on your requirements, plugins used, etc. Take a look at [doiuse](https://github.com/anandthakker/doiuse) if you want to know which browsers won't support some of your styles.
2. If you wanna use Tailwind for building emails, try @cossssmin's [Maizzle](https://maizzle.com/).

**Comment by natiki** [comment]
Thanks @hacknug
