### ISSUE TITLE
Config colors are not LessCSS color objects?

### ISSUE THREAD

**Issue by aphofstede** [tailwindcss/discuss#42]
In my app.less, I tried to use one of the configged colors in a Less function:

```
  @base_color: config('colors.grey');
  .input[type=text], .input[type=password] {
    background-color: fade(@base_color, 50%);
  }
```

This resulted in an error `Error evaluating function 'fade': color.toHSL is not a function`.
Is there a way around this? Am I wrong in expecting the colors array to contain Less color objects?

Here's my Mix config:

```
mix.js('frontend/assets/js/app.js', 'javascript/')
    .less('frontend/assets/less/app.less', 'style/')
    .options({
        extractVueStyles : true,
        postCss: [
            tailwindcss('tailwind.config.js'),
            require('autoprefixer')
        ]
    })
    .sourceMaps();
```

Alternatively: Is there another way to get transparent variants of the tailwind colors?

Thanks,
Alex

**Comment by adamwathan** [comment]
Hey @aphofstede! The reason this isn't working as you'd expect is that Less processes your CSS *before* Tailwind does; Tailwind is meant to work on Less' output.

That means that Less is literally trying to run the code `fade(config('colors.grey'), 50%)`, because Tailwind hasn't replaced the config call with the actual color value by the time Less is trying to apply the fade function.

The best way to add transparent variations of colors would be to add them as new colors in your `tailwind.js` config file.

Another approach that I bet would work is to use the [`postcss-color-function`](https://github.com/postcss/postcss-color-function) plugin, which would let you do that sort of alpha channel manipulation in the PostCSS phase:

```
.input[type=text], .input[type=password] {
    background-color: color(config('colors.grey'), a(50%));
}
```

I haven't tested it myself but it *should* work.

**Comment by aphofstede** [comment]
Thanks @adamwathan , that makes sense. It takes a bit of getting used to the pipeline I guess. (the PostCSS step is new, for me)

I added `'teal-lightest-half-transparent': 'rgba(232,255,254,0.5)',` to the colors array.
In my app.css it appears to have rendered correctly:
```
.bg-teal-lightest-half-transparent,
.hover\:bg-teal-lightest-half-transparent:hover {
	background-color: rgba(232, 255, 254, 0.5);
}
```

So I can do:
```
  input[type=text], input[type=password] {
    @apply .bg-teal-lightest-half-transparent;
  }
```

Yet I get `undefined` as a color if I try to do:
```
  input[type=text], input[type=password] {
    background-color: config('colors.teal-lightest-half-transparent');
  }
```
[the docs imply](https://tailwindcss.com/docs/colors/#customizing) that that should work?

**Comment by adamwathan** [comment]
@aphofstede Can you share a demo repo so I can try it out? Are you sure it's in the colors array and not just the `backgroundColors` array? Try `config('backgroundColors.teal-lightest-half-transparent')` and see if that makes a different 👍

**Comment by aphofstede** [comment]
Can't reproduce it anymore.. I think you might be right about the backgroundColors array actually, good instinct! 🤭 😄 Thanks

**Comment by chessydk** [comment]
I know this is closed, but unfortunately the trick with ``postcss-color-function`` won't work with LESS, because it has its own ``color`` function. The LESS compiler is therefor throwing an error and not passing it on to the postcss pipeline. I will try to make a PR to the lib so the name of the conversion function becomes  configurable.

**Comment by adamwathan** [comment]
One solution is to escape the string in less:

```
background: ~"color(red a(90%))";
```
