### ISSUE TITLE
@applying .container not working?

### ISSUE THREAD

**Issue by lperiodbose** [tailwindcss/discuss#44]
I've got a weird problem, and I'm not discounting user error, but figured someone could rubber-duck this with me...

The simple version of my problem is.

**html file**
`<div class="container"> </div>`

... is not doing the same thing as...

**html file**
`<div class="something-unique"></div>`

**scss file**
`.something-unique { @apply .container; }`

Specifically, Chrome never gets the `max-width` declarations when I'm using `@apply` that it does when I'm using the class.

I'm able to `@apply` all other sorts of things just fine. But container just doesn't work. Any thoughts? Something related to responsivity?

**Comment by adamwathan** [comment]
Hey @lperiodbose, you're right, applying `.container` to another class won't quite work as expected as it's a bit of a unique class in Tailwind.

Right now, `@apply` doesn't copy over any media query stuff because it introduces a *ton* of complexity and a ton of hard questions. It's meant to be used for simple utility classes only.

I'll probably look into having `@apply` explicitly throw an error if you try to apply a class that has media query definitions so at least there's a clear error message instead of just unexpected results.

If you want to create another class that behaves like the container, you can write it like this:

```
.something-unique {
    width: 100%;
}
@screen sm {
    .something-unique {
        max-width: config('screens.sm');
    }
}
@screen md {
    .something-unique {
        max-width: config('screens.md');
    }
}
@screen lg {
    .something-unique {
        max-width: config('screens.lg');
    }
}
@screen xl {
    .something-unique {
        max-width: config('screens.xl');
    }
}
```

**Comment by lperiodbose** [comment]
Got it! Thanks for clarifying, Adam!
