### ISSUE TITLE
Left align columns with css grid

### ISSUE THREAD

**Issue by melokki** [tailwindcss/discuss#463]
Hello,
I am experimenting the new css grid from tailwind and I've hit this problem and I don't have any idea how to solve it

As you can see in my pen, the `email address` is no aligned with the above `last name` at all and I was wondering how can I make them to stay left aligned no matter how long the text I enter it is. 

Any thoughts?

[here is my pen with what I did so far](https://codepen.io/melokki/pen/YzXpzWq)

**Comment by tlgreg** [comment]
That's because those are two separate grid containers, so these can't align with each other.
I'd probably would put them into a single `.grid` that flows horizontally and use `.col-span-*` on the "headers".
Something like this:
<https://codepen.io/tlgreg/pen/gOpLbNJ>
I also wrapped the "label + data" into a single div to retain source order.

**Comment by melokki** [comment]
I understand, thank you so so so much @tlgreg 🙏🙏
