### ISSUE TITLE
`@apply` cannot be used with .mt-8 because .mt-8 either does not exist, or it's actual definition includes a pseudo-class like :hover, :active, etc.

### ISSUE THREAD

**Issue by denjaland** [tailwindcss/discuss#71]
Hi,

First of all - great work on the project.  Looking forward to using this, and replacing our old bootstrap based CSS.

I was trying to do the following:
```css
h1, h2, h3, h4, h5, h6 {
    @apply .mt-8;
}
```
but when I compile (using Laravel Mix), I'm getting the following error:
```
`@apply` cannot be used with .mt-8 because .mt-8 either does not exist, or it's actual definition includes a pseudo-class like :hover, :active, etc.
```

How can I apply margins to my headings without having to add classes to all headings?  
I agree that most items we can simply apply utility classes, but someting such as `h` tags would be something I would like to apply the classes to throughout the project :-)

**Comment by denjaland** [comment]
Just wanted to add that I'm getting the same error, even when using the example from the docs:
```css
.btn {
    @apply .font-bold .py-2 .px-4 .rounded;
}
```
results in the error
```
ERROR in ./resources/assets/tailwind/app.css
Module build failed: ModuleBuildError: Module build failed: Syntax Error 

(2:5) `@apply` cannot be used with .font-bold because .font-bold either does not exist, or it's actual definition includes a pseudo-class like :hover, :active, etc.

  1 | .btn {
> 2 |     @apply .font-bold .py-2 .px-4 .rounded;
    |     ^
  3 | }

```

**Comment by adamwathan** [comment]
Can you share the whole file? It sounds like Tailwind’s utilities are not
being imported into your source file. Are you using a preprocessor like
Less or Sass or just plain CSS? If just plain CSS are you trying to use
imports but not using postcss-import?

**Comment by adamwathan** [comment]
Awesome ok, so the problem is right now your compiled CSS is just using plain boring CSS imports which won't work with `@apply`; Tailwind needs to be able to find those classes in the same tree of styles.

So the solution for you is to add `postcss-import` to your build chain, which will take all of your `@import` statements and actually inline them.

Run this:

```
# Using npm
npm install postcss-import

# Or if using yarn
yarn add postcss-import
```

Then add `postcss-import` before Tailwind in your `webpack.mix.js` file:

```diff
  let mix = require('laravel-mix').mix;
  var tailwindcss = require('tailwindcss');
+ let atImport = require('postcss-import');
  
  mix.options({
          purifyCss: true, // Remove unused CSS selectors.
      })
      .js('resources/assets/js/app.js', 'public/build/js')
      .minify('public/build/js/app.js')
      .extract(['vue'])
      .postCss('resources/assets/tailwind/app.css', 'public/build/tailwind', [
+         atImport(),
          tailwindcss('./tailwind.js'),
      ])
      .minify('public/build/tailwind/app.css')
      .version([]);
```

**Comment by denjaland** [comment]
Ok - you're brilliant.
I understand everything what you're saying.  The thing is I always wonder how one can know that this was the issue.
It did fix it, so I'm happy again, and will be able to continue migrating my layout to a new template - thanks so much for your assistance - MUCH appreciated!

**Comment by adamwathan** [comment]
Cool glad that helps!

Yeah you sort of need to have the right mental model of how `@apply` works to really understand why that would be the problem.

Basically, `@apply` can only apply classes from inside the same file, because it scans that file looking for a match.

By using `postcss-import` you are allowing yourself to keep things in separate files, but have everything get flattened into one file before Tailwind actually sees it, so by that time, `@apply` will work because all of your classes are now in the same file from Tailwind's perspective.

I'll see if I can think of a way to tweak the error messaging to help make that easier to understand, as well as update the documentation for that directive.

**Comment by denjaland** [comment]
Maybe add some links to an article in your docs for certain errors.  VueJS does that too, and it does help you to keep your error concise, but at the same time direct your users to more detailed information :-)

That being said - thanks again for a great product!  So far, love it!

**Comment by denjaland** [comment]
Closing to keep this great repo clean ;-)

**Comment by koryteg** [comment]
you can keep this closed but for anyone else getting this error. my problem was that we added a `tailwind.js` file and instead of extending the default theme, we overwrote the existing one. which mean those classes would actually never get created.

the fix here is to extend the theme instead of overwriting it.

**Comment by eriknyk** [comment]
how this can be fixed in a regular, i.e react app?

I've tried:

```
//postcss.config.js
const tailwindcss = require('tailwindcss');
const atImport = require('postcss-import');

module.exports = {
 plugins: [
   atImport(),
   tailwindcss('./tailwind.js'),
   require('autoprefixer'),
 ],
};
```
But I'm still getting the related error:

```
CssSyntaxError: /Users/erik/Projects/webapp/src/styles/tailwind.css:78:3: `@apply` cannot be used with `.focus\:outline-none` because `.focus\:outline-none` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.focus\:outline-none` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

Any help will be appreciated.

**Comment by adamwathan** [comment]
Hey! This is explained here in the docs:

https://tailwindcss.com/docs/functions-and-directives#apply

> It's important to understand that @apply will not work for inlining pseudo-class or responsive variants of another utility. Instead, apply the plain version of that utility into the appropriate pseudo-selector or a new media query:

```css
/* Won't work: */
.btn {
  @apply block bg-red-500;
  @apply hover:bg-blue-500;
  @apply md:inline-block;
}

/* Do this instead: */
.btn {
  @apply block bg-red-500;
}
.btn:hover {
  @apply bg-blue-500;
}
@screen md {
  .btn {
    @apply inline-block;
  }
}
```

**Comment by eriknyk** [comment]
Thank you @adamwathan
